CREATE TABLE users(
	id INT PRIMARY KEY IDENTITY(1,1),
	username VARCHAR(MAX) NULL,
	password VARCHAR(MAX) NULL,
	date_create DATE NULL
)

SELECT * FROM users

CREATE TABLE expenses(
	id INT PRIMARY KEY IDENTITY(1,1),
	type VARCHAR(MAX) NULL,
	name VARCHAR(MAX) NULL,
	date DATE NULL,
	amount DECIMAL(38,2) NULL,
	grace VARCHAR(MAX) NULL,
	lateFee DECIMAL(38,2) NULL,
	passed VARCHAR(MAX) NULL,
	passedAmount DECIMAL(38,2) NULL,
	creditIssue VARCHAR(MAX) NULL
)

SELECT * FROM expenses

CREATE TABLE income(
	id INT PRIMARY KEY IDENTITY(1,1),
	type VARCHAR(MAX) NULL,
	name VARCHAR(MAX) NULL,
	date DATE NULL,
	amount DECIMAL(38,2) NULL,
)

SELECT * FROM income

ALTER TABLE expenses ADD
	category VARCHAR(MAX) NULL;
